---
title: "HfpEF Transcriptomics Repositories"
authors: 
    - name: "Ludimila Araújo"
      affiliation: "BioME / UFRN"
      email: "dearaujo.ludimila@gmail.com"

    - name: "Caio César"
      affiliation: "BioME / UFRN"
      email: "caiocs.maia@gmail.com"
format: 
    html: 
        theme: flatly
        css: styles/custom.scss
        toc: true
        toc-title: "Table of Contents"
execute:
    echo: false #versão final exibirá apenas textos, gráficos e tabelas geradas; linhas de código ocultas dos leitores.
    warning: false
---

# Introduction

This report provides a standardized survey of transcriptomic datasets (bulk RNA-seq, scRNA-seq, and snRNA-seq) associated with Heart Failure with preserved Ejection Fraction (HFpEF).

# Metadata Dictionary

The repository consolidates biological metadata, experimental designs, and sequencing specifications to streamline bioinformatics workflows and comparative analyses.

```{python}
from hfpef_catalog.data_loader import load_all_species

df_species = load_all_species()

print(df_species.keys())
```

```{python}
from hfpef_catalog.processing import count_all_species

total_species = count_all_species(df_species)

print(total_species)

```

```{python}
from hfpef_catalog.processing import sum_all_repositories

total_repo = sum_all_repositories(df_species)
print(total_repo)

```


# Repositories Overview

::: {.columns}

::: {.column width="50%"}

### Cataloged Species

# `{python} total_species`

:::

::: {.column width="50%"}

### Repositories

# `{python} total_repo`

:::

:::

## Repositories Details

```{python}
from hfpef_catalog.processing import get_species_overview

felis_overview = get_species_overview(df_species["felis_catus"])
homo_overview = get_species_overview(df_species["homo_sapiens"])
mus_overview = get_species_overview(df_species["mus_musculus"])
```

<details>
<summary><strong>Felis catus</strong></summary>

### Species Overview

::: {.columns}

::: {.column width="50%"}

<div class="overview-card">

<p class="overview-label">Dataset ID</p>

<p class="overview-value">`{python} felis_overview["Dataset ID"]`</p>

</div>

<div class="overview-card">

<p class="overview-label">Sampled Tissue</p>

<p class="overview-value">`{python} felis_overview["Sampled tissue"]`</p>

</div>

<div class="overview-card">

<p class="overview-label">Strain / ethnicity</p>

<p class="overview-value">`{python} felis_overview["Strain / ethnicity"]`</p>

</div>

:::

::: {.column width="50%"}

<div class="overview-card">

<p class="overview-label">Sex</p>

<p class="overview-value">`{python} felis_overview["Sex"]`</p>

</div>

<div class="overview-card">

<p class="overview-label">Biosamples</p>

<p class="overview-value">`{python} felis_overview["Biosamples"]`</p>

</div>

<div class="overview-card">

<p class="overview-label">Conditions</p>

<p class="overview-value">`{python} felis_overview["Conditions"]`</p>

</div>

:::

:::

</details>

<details>
<summary><strong>Homo sapiens</strong></summary>

</details>

<details>
<summary><strong>Mus musculus</strong></summary>

</details>



```{python}
for species, df in df_species.items():
    overview = get_species_overview(df)

    print(species)
    print(overview)
    print()
```